# Ways to the Game of Life -- The Third Way

*Here we continue upon our dual-purpose journey: to learn Python by implementing
a version of Conway's Game of Life. Here we assume you have completed the
previous notebooks to your satisfaction.*

Previously we examined implementations restricting ourselves first to base
Python, then a sparse implementation that used `Counter` from the standard
library. Recall the expanded ***learning by doing*** process we introduced
in the first notebook, specifically the order of exploration for imports. In
practice we will find ourselves using `numpy` for  scientific computing.

What is `numpy`? Again, per our professional, scientific approach we prefer
to directly consult source documentation:

> NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

You should take the time now to read the [What is NumPy?](https://numpy.org/doc/stable/user/whatisnumpy.html) page yourself now.

---

That done, it is time to get pushed back into the Python pool.

The way we import numpy here is  the de-facto standard. So much so that you
can presume `np` to mean `numpy` in general discussions online (code must
obviously explicitly import numpy).

In [1]:
import numpy as np

Jupyter notebooks and other interactive coding environments often have a
tab-complete feature which allows us to examine (basically) the `dir()`
of a given object. Try that now with `np.[tab]`.

The NumPy package is expansive, but you fill find most of your use is
centered around what is an `np.ndarray` object, which you will most often
create with a call to `np.array()`. This is similar to how we often create
a `List` type by calling `list()`. We will examine the mechanics behind this
in a later lesson, for now remember to use `type()` if you are not sure of
your object type.

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
# Why does this not work?
# np.array(0, 1, 2, 3, 4, 5)

For our convenience there are array creation routines, for our purpose
we will find the `np.zeros()` creation routine particularly useful.

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

For now it may not make much of a difference, but it is good form
to use the `int` type when we know we will using natural numbers.

In [6]:
np.zeros(5, int)

array([0, 0, 0, 0, 0])

Indeed, if we provide a two-dimensional argument to the shape input, we
can instantiate an empty grid very easily.

In [7]:
empty_grid = np.zeros((5, 5), int)
empty_grid

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Now, previously we indexed lists of lists. That is **not the case** here.
Recall that we have a single `np.ndarray` object, *not* a nested list of lists.

Now is a good time to read the [Array Indexing](https://numpy.org/doc/stable/user/basics.indexing.html) page, you need not commit this to memory now, on the other hand
you should surely save such a reference now.

In [ ]:
np.array([])

In [8]:
# Do this in numpy:
empty_grid[0, 0]

# Not this, even if it works, read why in the link above.
# empty_grid[0][0]

0

In [9]:
type(empty_grid)

numpy.ndarray

Now, let us compare the use of operators on `numpy.ndarray` and on `list` objects.

In [22]:
demo_list = list(range(5))
demo_list

[0, 1, 2, 3, 4]

In [23]:
demo_array = np.array(range(5))
demo_array

array([0, 1, 2, 3, 4])

The addition operator.

Attempting to add an integer produces an error:

In [28]:
# Produces TypeError. 
demo_list + 1

TypeError: can only concatenate list (not "int") to list

While the same operation on a `numpy.ndarray` object produces a result:

In [29]:
demo_array + 1

array([1, 2, 3, 4, 5])

The process of applying these operations across compatible array shapes is called [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html). That topic will be of great interest and importance in the future, but for now we can be satisfied with the observation that our operation is carried out for each member of our array.

The operators are described in the [Built-in Types](https://docs.python.org/3/library/stdtypes.html#index-7) section of the documentation.

Here we will make use of the remainder operator: `%`

This operator gives the remainder after a division.

In [31]:
demo_array

array([0, 1, 2, 3, 4])

In [33]:
demo_array % 2

array([0, 1, 0, 1, 0])

For our application to the Game of Life, we can use this to determine the 'wrapped' index.

So you can better observe what is happening, will use a new grid.

In [34]:
ordered_grid = np.arange(25).reshape(5,5)
ordered_grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

The shape of the array gives the divisor for wrapping or coordinates:

In [37]:
ordered_grid.shape

(5, 5)

It would be nice to see the result of our operation on a range of requested coordinates...

In [48]:
coords = list()

for x in range(-1, 6):
    for y in range(-1, 6):
        coords.append((x,y))

# Equivalent code in the generator syntax.
# coords = [(x, y) for x in range(5) for y in range(5)]
# coords

Let us convert this to a `numpy` array, this should allow us to see the result of our function on our the coordinates likely to be requested by our code.

In [51]:
coord_array = np.array(coords)
coord_array

array([[-1, -1],
       [-1,  0],
       [-1,  1],
       [-1,  2],
       [-1,  3],
       [-1,  4],
       [-1,  5],
       [ 0, -1],
       [ 0,  0],
       [ 0,  1],
       [ 0,  2],
       [ 0,  3],
       [ 0,  4],
       [ 0,  5],
       [ 1, -1],
       [ 1,  0],
       [ 1,  1],
       [ 1,  2],
       [ 1,  3],
       [ 1,  4],
       [ 1,  5],
       [ 2, -1],
       [ 2,  0],
       [ 2,  1],
       [ 2,  2],
       [ 2,  3],
       [ 2,  4],
       [ 2,  5],
       [ 3, -1],
       [ 3,  0],
       [ 3,  1],
       [ 3,  2],
       [ 3,  3],
       [ 3,  4],
       [ 3,  5],
       [ 4, -1],
       [ 4,  0],
       [ 4,  1],
       [ 4,  2],
       [ 4,  3],
       [ 4,  4],
       [ 4,  5],
       [ 5, -1],
       [ 5,  0],
       [ 5,  1],
       [ 5,  2],
       [ 5,  3],
       [ 5,  4],
       [ 5,  5]])

As always, examine the shape of this object.

In [52]:
coord_array.shape

(49, 2)

Now let us write a function that wraps out of bonds requests.

In [53]:
def wrap_coords(coordinates, shape=(5,5)):
    wrapped_coords = coordinates % shape
    return wrapped_coords


wrap_coords(coord_array)

array([[4, 4],
       [4, 0],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4],
       [4, 0],
       [0, 4],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [0, 0],
       [1, 4],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 0],
       [2, 4],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [2, 0],
       [3, 4],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3],
       [3, 4],
       [3, 0],
       [4, 4],
       [4, 0],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4],
       [4, 0],
       [0, 4],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [0, 0]])

NumPy is an extremely powerful package that we have just barely touched on here. I
encourage you to take a goal-oriented approach in exploring `numpy` (and other packages).
Often times the lens provided by a problem or goal is required to clarify the 'why'
to a program.

The challenge proposed here is to (again) implement the game of life, this time
using a `numpy.ndarray` to model the grid.