In [3]:
import numpy as np

In [4]:
np.array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

In [5]:
# Why does this not work?
# np.array(0, 1, 2, 3, 4, 5)

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros(5, int)

array([0, 0, 0, 0, 0])

In [8]:
empty_grid = np.zeros((5, 5), int)
empty_grid

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Numpy indexing

Now, previously we indexed lists of lists. That is **not the case**
here.

Here we have a single Python object:

In [9]:
# Do this in numpy:
empty_grid[0, 0]

# Not this, even if it works.
# empty_grid[0][0]

0

In [10]:
type(empty_grid)

numpy.ndarray

Here is the good stuff. *What is happening here?*

In [13]:
empty_grid.take([0, 8])

array([0, 0])