# Ways to the Game of Life -- The Third Way

*Here we continue upon our dual-purpose journey: to learn Pyton by implementing
a version of Conway's Game of Life. Here we assume you have completed the
previous notebooks to your satisfaction.*

Previously we examined implementations restricting ourselves first to base
Python, then a sparse implementation that used `Counter` from the standard
library. Recall the expanded ***learning by doing*** process we introduced
in the first notebook, specifically the order of exploration for imports. In
practice we will find ourselves using `numpy` for  scientific computing.

What is `numpy`? Again, per our professional, scientific approach we prefer
to directly consult source documentation:

> NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

You should take the time now to read the [What is NumPy?](https://numpy.org/doc/stable/user/whatisnumpy.html) page yourself now.

---

That done, it is time to get pushed back into the Python pool.

The way we import numpy here is  the de-facto standard. So much so that you
can presume `np` to mean `numpy` in general discussions online (code must
obviously explicitly import numpy).

In [1]:
import numpy as np

Jupyter notebooks and other interactive coding environments often have a
tab-complete feature which allows us to examine (basically) the `dir()`
of a given object. Try that now with `np.[tab]`.

The NumPy package is expansive, but you fill find most of your use is
centered around what is an `np.ndarray` object, which you will most often
create with a call to `np.array()`. This is similar to how we often create
a `List` type by calling `list()`. We will examine the mechanics behind this
in a later lesson, for now remember to use `type()` if you are not sure of
your object type.

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
# Why does this not work?
# np.array(0, 1, 2, 3, 4, 5)

For our convenience there are array creation routines, for our purpose
we will find the `np.zeros()` creation routine particularly useful.

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

For now it may not make much of a difference, but it is good form
to use the `int` type when we know we will using natural numbers.

In [5]:
np.zeros(5, int)

array([0, 0, 0, 0, 0])

Indeed, if we provide a two-dimensional argument to the shape input, we
can instantiate an empty grid very easily.

In [7]:
empty_grid = np.zeros((5, 5), int)
empty_grid

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Now, previously we indexed lists of lists. That is **not the case** here.
Recall that we have a single `np.ndarray` object, *not* a nested list of lists.

Now is a good time to read the [Array Indexing](https://numpy.org/doc/stable/user/basics.indexing.html) page, you need not commit this to memory now, on the other hand
you should surely save such a reference now.

In [8]:
# Do this in numpy:
empty_grid[0, 0]

# Not this, even if it works, read why in the link above.
# empty_grid[0][0]

0

In [10]:
type(empty_grid)

numpy.ndarray

I want to convince the new programmer that the use of `numpy` is worthwhile,
moreover, I want to convince you that our ***learning by doing*** approach is
something that will naturally grow into a professional one.

I hope you can picture your future self examining the `numpy` package as we have
done together here. Surely with enough time you would come across a function
`np.ndarray.take()`, perhaps in the tab-complete or call to `dir()`, or by
simply skimming the reference documentation.

In [10]:
help(np.take)

Help on function take in module numpy:

take(a, indices, axis=None, out=None, mode='raise')
    Take elements from an array along an axis.
    
    When axis is not None, this function does the same thing as "fancy"
    indexing (indexing arrays using arrays); however, it can be easier to use
    if you need elements along a given axis. A call such as
    ``np.take(arr, indices, axis=3)`` is equivalent to
    ``arr[:,:,:,indices,...]``.
    
    Explained without fancy indexing, this is equivalent to the following use
    of `ndindex`, which sets each of ``ii``, ``jj``, and ``kk`` to a tuple of
    indices::
    
        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        Nj = indices.shape
        for ii in ndindex(Ni):
            for jj in ndindex(Nj):
                for kk in ndindex(Nk):
                    out[ii + jj + kk] = a[ii + (indices[jj],) + kk]
    
    Parameters
    ----------
    a : array_like (Ni..., M, Nk...)
        The source array.
    indices : array_like (Nj...

Check out that last parameter, or function option:
```text
 mode : {'raise', 'wrap', 'clip'}, optional
        Specifies how out-of-bounds indices will behave.

        * 'raise' -- raise an error (default)
        * 'wrap' -- wrap around
        * 'clip' -- clip to the range

        'clip' mode means that all indices that are too large are replaced
        by the index that addresses the last element along that axis. Note
        that this disables indexing with negative numbers.
```

NumPy is an extremely powerful package that we have just barely touched on here. I
encourage you to take a goal-oriented approach in exploring `numpy` (and other packages).
Often times the lens provided by a problem or goal is required to clarify the 'why'
to a program.

In [13]:
empty_grid.take([0, 8])

array([0, 0])

The challenge proposed here is to (again) implement the game of life, this time
using a `numpy.ndarray` to model the grid.